"""Initial migration

Revision ID: 52bbe8b7cc08
Revises: 0fa911d2ce5a
Create Date: 2024-02-27 23:32:38.416084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bbe8b7cc08'
down_revision: Union[str, None] = '0fa911d2ce5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
