"""description of changes

Revision ID: a05eceedba88
Revises: 38f08ef79606
Create Date: 2024-02-23 14:14:48.858537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05eceedba88'
down_revision: Union[str, None] = '38f08ef79606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tokens_id', table_name='user_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_tokens_id', 'user_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
